name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name || github.run_id }} 
  cancel-in-progress: true

jobs:

  check-juliaup:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        label: [
          x86_64-pc-windows-msvc-windowsstore,
          x86_64-pc-windows-msvc-windowsappinstaller,
          x86_64-apple-darwin,
          x86_64-unknown-linux-gnu,
          i686-pc-windows-msvc-windowsstore,
          i686-pc-windows-msvc-windowsappinstaller,
          i686-unknown-linux-gnu,
          aarch64-unknown-linux-gnu,
          aarch64-apple-darwin
          ]
        include:
          - label: x86_64-pc-windows-msvc-windowsstore
            target: x86_64-pc-windows-msvc
            os: windows
            features: windowsstore
            rustflags:
          - label: x86_64-pc-windows-msvc-windowsappinstaller
            target: x86_64-pc-windows-msvc
            os: windows
            features: windowsappinstaller
            rustflags:
          - label: x86_64-apple-darwin
            target: x86_64-apple-darwin
            os: macos
            features: selfupdate
            rustflags:
          - label: x86_64-unknown-linux-gnu
            target: x86_64-unknown-linux-gnu
            os: ubuntu
            features: selfupdate
            rustflags:
          - label: i686-pc-windows-msvc-windowsstore
            target: i686-pc-windows-msvc
            os: windows
            features: windowsstore
            rustflags:
          - label: i686-pc-windows-msvc-windowsappinstaller
            target: i686-pc-windows-msvc
            os: windows
            features: windowsappinstaller
            rustflags:
          - label: i686-unknown-linux-gnu
            target: i686-unknown-linux-gnu
            os: ubuntu
            features: selfupdate
            rustflags:
          - label: aarch64-unknown-linux-gnu
            target: aarch64-unknown-linux-gnu
            os: ubuntu
            features: selfupdate
            rustflags:
          - label: aarch64-apple-darwin
            target: aarch64-apple-darwin
            os: macos
            features: selfupdate
            rustflags:
    steps:
    - uses: actions/checkout@v3
    - if: ${{ contains(matrix.target, '-musl') }}
      container:
        image: alpine:latest
      steps:
        - name: Prepare alpine container
          run: |
            sudo apk add pkgconfig openssl-dev musl-dev gcc cargo

        - name: Check build
          run: |
            cargo check --release --bins --target ${{matrix.target}} --features ${{matrix.features}}

    - if: ${{ matrix.os == 'ubuntu' }}
      run: sudo apt-get install libssl-dev pkg-config
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        target: ${{matrix.target}}
    - name: Check build
      uses: actions-rs/cargo@v1
      with:
        command: check
        use-cross: ${{ matrix.os == 'ubuntu' }}
        args: --release --bins --target ${{matrix.target}} --features ${{matrix.features}}
      env:
        CARGO_TARGET_x86_64-unknown-linux-musl: ${{matrix.rustflags}}
        CARGO_TARGET_i686-unknown-linux-musl: ${{matrix.rustflags}}
        CARGO_TARGET_aarch64-unknown-linux-musl: ${{matrix.rustflags}}

  test-juliaup:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        target: [
          x86_64-pc-windows-msvc,
          x86_64-apple-darwin,
          x86_64-unknown-linux-gnu,
          x86_64-unknown-linux-musl,
          i686-pc-windows-msvc,
          ]
        include:
          - target: x86_64-pc-windows-msvc
            os: windows
            features: dummy
            rustflags:
          - target: x86_64-apple-darwin
            os: macos
            features: dummy
            rustflags:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
            features: dummy
            rustflags:
          - target: x86_64-unknown-linux-musl
            os: ubuntu
            features: dummy
            rustflags: -C target-feature=+crt-static
          - target: i686-pc-windows-msvc
            os: windows
            features: dummy
            rustflags:
    steps:
    - uses: actions/checkout@v3
    - if: ${{ contains(matrix.target, '-musl') }}
      container:
        image: alpine:latest
      steps:
        - name: Prepare alpine container
          run: |
            sudo apk add pkgconfig openssl-dev musl-dev gcc cargo

        - name: Test
          run: |
            cargo test --target ${{matrix.target}} --features ${{matrix.features}}

    - if: ${{ matrix.os == 'ubuntu' }}
      run: sudo apt-get install libssl-dev pkg-config
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        target: ${{matrix.target}}
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --target ${{matrix.target}} --features ${{matrix.features}}
      env:
        CARGO_TARGET_x86_64-unknown-linux-musl: ${{matrix.rustflags}}
        CARGO_TARGET_i686-unknown-linux-musl: ${{matrix.rustflags}}
        CARGO_TARGET_aarch64-unknown-linux-musl: ${{matrix.rustflags}}
