name: Test(Musl)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name || github.run_id }} 
  cancel-in-progress: true

jobs:

  build:
    runs-on: ${{ matrix.platform }}

    container:
      image: 'alpine:latest'
      options: --platform=linux/${{ matrix.platform }}

    strategy:
      fail-fast: false
      matrix:
        platform: [armv7, aarch64, x86_64, i686]

    steps:
      - uses: actions/checkout@v3
      - name: Prepare container
        run: |
          sudo apk add pkgconfig openssl-dev musl-dev gcc cargo

      - name: Check
        run: |
          cargo check --release --bins --features selfupdate

      - name: Test
        run: |
          cargo test --features selfupdate
